---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: "Include docker-bare-metal"
      include_role:
        name: "docker-bare-metal"
      vars:
        docker_insecure_registries: "{{ lookup('env', 'INSECURE_REGISTRIES') }}"
        docker_registry_mirrors: "{{ lookup('env', 'DOCKER_REGISTRY_MIRRORS') }}"
        docker_allow_forward: true
